10 REM HILO -- guess the number; shows INPUT fed from stdin,
20 REM --seed for repeatable RND, and a non-zero exit via ERROR.
30 CLS: PRINT "I'M THINKING OF A NUMBER FROM 1 TO 100."
40 N=RND(100): T=0: LO=1: HI=100
50 T=T+1: PRINT: PRINT "GUESS #";T;: INPUT G
60 IF G<1 OR G>100 THEN PRINT "THAT'S NOT EVEN ON THE BOARD.": GOTO 50
70 IF G=N THEN 200
80 IF G<N THEN PRINT "TOO LOW.";: LO=G+1 ELSE PRINT "TOO HIGH.";: HI=G-1
90 IF HI-LO<0 THEN PRINT " ...YOU CONTRADICT YOURSELF. I QUIT.": ERROR 1
100 PRINT " (IT'S BETWEEN";LO;"AND";HI;")"
110 IF T<7 THEN 50
120 PRINT "SEVEN TRIES IS ALL YOU GET. IT WAS";N;".": END
200 PRINT "YES!";N;"IN";T;"TRIES.";
210 IF T<=7 THEN PRINT " BINARY SEARCH WOULD BE PROUD." ELSE PRINT
