10 REM TRAPPER -- error handling: ON ERROR GOTO, ERR, ERL, RESUME,
20 REM and ERROR n to raise one on purpose.  A calculator that
30 REM refuses to die no matter what you feed it.
40 CLS: ON ERROR GOTO 200
50 READ A$,B$: IF A$="END" THEN 300
60 A=VAL(A$): B=VAL(B$)
70 Q=A/B: PRINT A$;"/";B$;" = ";Q
80 GOTO 50
200 C=ERR/2+1
210 IF C=11 THEN PRINT A$;"/";B$;" -- DIVISION BY ZERO, SKIPPED": RESUME 50
220 PRINT "ERROR CODE";C;"AT LINE";ERL: RESUME NEXT
300 PRINT: PRINT "NOW RAISING ONE ON PURPOSE...": ERROR 8
310 PRINT "STILL HERE. HANDLER RETURNED CONTROL TO LINE 310."
320 ON ERROR GOTO 0: PRINT "TRAP REMOVED; ERROR 2 NOW RAISES A REAL ?SN:"
330 ERROR 2
340 DATA 10,4, 7,0, 22,7, END,END
