10 REM ' is :REM -- the ROM crunches it to 3AH 93H FBH -- so it ends the statement before it
20 F=0:N=0
30 FOR I=1 TO 3:N=N+1:NEXT 'A BARE NEXT BEFORE A COMMENT
40 IF N<>3 THEN PRINT "FAIL: NEXT 'COMMENT, N=";N:F=1
50 N=0:FOR I=1 TO 2:N=N+1:NEXT'NO BLANK
60 IF N<>2 THEN PRINT "FAIL: NEXT'COMMENT, N=";N:F=1
70 A=5 'AFTER AN ASSIGNMENT
80 IF A<>5 THEN PRINT "FAIL: A=5 'COMMENT":F=1
90 IF 0 THEN F=1 ELSE A=6 'AFTER ELSE
100 IF A<>6 THEN PRINT "FAIL: ELSE 'COMMENT":F=1
110 RESTORE:READ D$:IF D$<>"IT'S" THEN PRINT "FAIL: ' INSIDE DATA IS TEXT, D$=";D$:F=1
120 DATA IT'S
130 IF F THEN PRINT "APOSTROPHE FIXTURE FAILED":ERROR 5
140 PRINT "APOSTROPHE OK"
